=== Guillaume06/BD-Polytech/SI.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="si" type="siType"/>

  <xs:complexType name="siType">
    <xs:sequence>
      <xs:element type="annéesType" name="années"/>
      <xs:element type="étudiantsType" name="étudiants"/>
      <xs:element type="enseignantsType" name="enseigneants"/>
      <xs:element type="sallesType" name="salles"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="annéesType">
    <xs:sequence>
      <xs:element type="annéeType" name="année" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="annéeType">
    <xs:sequence>
      <xs:element type="enseignementsType" name="enseignements"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="enseignementsType">
    <xs:sequence>
      <xs:element type="enseignementType" name="enseignement" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="enseignementType">
    <xs:sequence>
      <xs:element type="xs:string" name="matière"/>
      <xs:element type="xs:string" name="date"/>
      <xs:element type="xs:string" name="salle"/>
      <xs:element type="xs:string" name="enseignant"/>
    </xs:sequence>
    <xs:attribute name="filière" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="étudiantsType">
    <xs:sequence>
      <xs:element type="étudiantType" name="étudiant" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="étudiantType">
    <xs:attribute name="année" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="nom" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="prénom" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="filière" type="xs:string"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="enseignantsType">
    <xs:sequence>
      <xs:element type="xs:string" name="enseignant" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sallesType">
    <xs:sequence>
      <xs:element type="xs:string" name="salle" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Guillaume06/BD-Polytech/SI.xml
<?xml version="1.0" encoding="UTF-8" standalone='no'?>

<!DOCTYPE cv SYSTEM "SI.dtd">

<si xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SI.xsd">

    <années>
        <année type="SI3">
            <enseignements>
                <enseignement filière="">
                    <matière></matière>
                    <date></date>
                    <salle></salle>
                    <enseignant></enseignant>
                </enseignement>
            </enseignements>
        </année>
        <année type="SI4">
            <enseignements>
                <enseignement filière="">
                    <matière></matière>
                    <date></date>
                    <salle></salle>
                    <enseignant></enseignant>
                </enseignement>
            </enseignements>
        </année>
        <année type="SI5">
            <enseignements>
                <enseignement filière="">
                    <matière></matière>
                    <date></date>
                    <salle></salle>
                    <enseignant></enseignant>
                </enseignement>
            </enseignements>
        </année>
    </années>

    <étudiants>
        <étudiant année="SI3" nom="Barathéon" prénom="Robert"></étudiant>
        <étudiant année="SI3" nom="Barathéon" prénom="Stannis"></étudiant>
        <étudiant année="SI4" nom="Stark" prénom="Sansa"></étudiant>
        <étudiant année="SI4" nom="Stark" prénom="Arya"></étudiant>
        <étudiant année="SI5" nom="Barathéon" prénom="Joeffrey" filière="CASPAR"></étudiant>
        <étudiant année="SI5" nom="Lannister" prénom="Tyrion" filière="AL"></étudiant>
        <étudiant année="SI5" nom="Lannister" prénom="Jaime" filière="WEB"></étudiant>
        <étudiant année="SI5" nom="Lannister" prénom="Cersei" filière="IMAFA"></étudiant>
    </étudiants>

    <enseigneants>
        <enseignant>M Dupond</enseignant>
        <enseignant>Mme Dupont</enseignant>
        <enseignant>Mme Dupond</enseignant>
        <enseignant>M Dupont</enseignant>
        <enseignant>Mlle Dupond</enseignant>
        <enseignant>Mlle Dupont</enseignant>
        <enseignant>M Tupont</enseignant>
        <enseignant>Mme Tupond</enseignant>
    </enseigneants>

    <salles>
        <salle>S-200</salle>
        <salle>S-100</salle>
        <salle>E-200</salle>
        <salle>E-100</salle>
        <salle>E+100</salle>
        <salle>O+100</salle>
        <salle>O+200</salle>
        <salle>O+300</salle>
    </salles>

</si>
